baseURL = "http://waiting-tables.com/"
languageCode = "en-us"
title = "Waiting Tables"
theme = "bootstrap"

[params]
    email = "tim@waiting-tables.com?subject=Waiting Tables Feedback"
    twitter = "_waitingtables_"
[[menu.main]]
    name = "about"
    pre = "<i class='fa fa-question'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
