baseURL = "https://waiting-tables.netlify.app"
languageCode = "en_US"
title = "Waiting Tables"
theme = "bootstrap"
DisqusShortname = "waiting-tables"

[params]
twitter = "_waitingtables_"
[[menu.main]]
    name = "about"
    pre = "<i class='fa fa-question'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
