baseURL = "http://waiting-tables.com/"
languageCode = "en-us"
title = "Waiting Tables Podcast"
theme = "bootstrap"

[[menu.main]]
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
